# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pearson_fast <- function(seed, query) {
    .Call('_vesalius_pearson_fast', PACKAGE = 'vesalius', seed, query)
}

pearson_exact <- function(seed, query) {
    .Call('_vesalius_pearson_exact', PACKAGE = 'vesalius', seed, query)
}

jaccard_cost <- function(seed, query) {
    .Call('_vesalius_jaccard_cost', PACKAGE = 'vesalius', seed, query)
}

