# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pearson_fast <- function(seed, query) {
    .Call('_vesalius_pearson_fast', PACKAGE = 'vesalius', seed, query)
}

pearson_exact <- function(seed, query) {
    .Call('_vesalius_pearson_exact', PACKAGE = 'vesalius', seed, query)
}

jaccard_cost <- function(seed, query) {
    .Call('_vesalius_jaccard_cost', PACKAGE = 'vesalius', seed, query)
}

bubble_stack_optimized <- function(coordinates, n_centers = 500L, max_iter = 500L) {
    .Call('_vesalius_bubble_stack_optimized', PACKAGE = 'vesalius', coordinates, n_centers, max_iter)
}

