# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

feature_cost <- function(seed, query) {
    .Call('_vesalius_feature_cost', PACKAGE = 'vesalius', seed, query)
}

compare_niche_fast <- function(seed, query) {
    .Call('_vesalius_compare_niche_fast', PACKAGE = 'vesalius', seed, query)
}

