name: R-CMD-BiocCheck

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  R-CMD-BiocCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("remotes")'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Install renv
        run: Rscript -e 'install.packages("renv")'

      - name: Restore project environment from renv.lock
        run: Rscript -e 'renv::restore()'

      - name: Build package
        run: R CMD build .

      - name: Check package
        run: R CMD BiocCheck *.tar.gz
